# Generated by Django 5.0.9 on 2026-09-23 10:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0002_hardlogoutevent_hardlogouttargetresult_session_and_more'),
        ('customers', '0001_initial'),
        ('organizations', '0001_initial'),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('REFUNDED', 'Refunded'), ('CANCELLED', 'Cancelled')], default='COMPLETED', max_length=20)),
                ('sold_at', models.DateTimeField()),
                ('access_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='access.accessplan')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='customers.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='organizations.organization')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='places.place')),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='access.voucher')),
            ],
            options={
                'db_table': 'commercial_sale',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('status', models.CharField(choices=[('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='SUCCEEDED', max_length=20)),
                ('reference', models.CharField(blank=True, help_text='External payment reference', max_length=255)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='commercial.sale')),
            ],
            options={
                'db_table': 'commercial_transaction',
            },
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['organization', 'sold_at'], name='commercial__organiz_84e87c_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['place', 'sold_at'], name='commercial__place_i_dcc8b9_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['access_plan'], name='commercial__access__7d3d2b_idx'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(check=models.Q(('total__gte', 0)), name='sale_total_non_negative'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['sale'], name='commercial__sale_id_7cc2de_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_at'], name='commercial__created_c2ec4b_idx'),
        ),
    ]
