# Generated by Django 5.0.9 on 2026-09-20 04:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(db_index=True, max_length=100)),
                ('key', models.CharField(max_length=255)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('response_status', models.IntegerField()),
                ('response_body', models.JSONField()),
            ],
            options={
                'db_table': 'common_idempotency_record',
            },
        ),
        migrations.AddConstraint(
            model_name='idempotencyrecord',
            constraint=models.UniqueConstraint(fields=('scope', 'key'), name='unique_idempotency_key_per_scope'),
        ),
    ]
