# Generated by Django 5.0.9 on 2026-09-22 10:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('max_places', models.PositiveIntegerField(blank=True, help_text='Null = unlimited', null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing_period', models.CharField(choices=[('MONTHLY', 'Monthly'), ('ANNUAL', 'Annual')], default='MONTHLY', max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
            ],
            options={
                'db_table': 'platform_admin_plan',
            },
        ),
        migrations.CreateModel(
            name='OrganizationSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='organizations.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='platform_admin.plan')),
            ],
            options={
                'db_table': 'platform_admin_organizationsubscription',
            },
        ),
        migrations.CreateModel(
            name='PlatformStaff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('SUPERADMIN', 'Super admin'), ('SUPPORT', 'Support'), ('BILLING', 'Billing')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='platform_staff', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'platform_admin_platformstaff',
            },
        ),
        migrations.CreateModel(
            name='PlatformActivityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=500)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_activity_events', to='organizations.organization')),
            ],
            options={
                'db_table': 'platform_admin_platformactivityevent',
                'indexes': [models.Index(fields=['organization', 'created_at'], name='platform_ad_organiz_1fedd9_idx')],
            },
        ),
    ]
