# Generated by Django 5.0.9 on 2026-09-21 06:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_type', models.CharField(choices=[('STAFF', 'Staff user'), ('SYSTEM', 'System/worker'), ('CUSTOMER', 'Customer/portal user')], max_length=20)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('resource_type', models.CharField(max_length=100)),
                ('resource_id', models.CharField(max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='organizations.organization')),
            ],
            options={
                'db_table': 'audit_auditevent',
                'indexes': [models.Index(fields=['organization', 'created_at'], name='audit_audit_organiz_4fc53a_idx'), models.Index(fields=['resource_type', 'resource_id'], name='audit_audit_resourc_2ab5ff_idx'), models.Index(fields=['action'], name='audit_audit_action_203f66_idx')],
            },
        ),
    ]
