# Generated by Django 5.0.9 on 2026-09-19 16:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor_code', models.CharField(choices=[('MIKROTIK', 'Mikrotik')], max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('encrypted_credentials', models.BinaryField()),
                ('status', models.CharField(choices=[('PENDING_VERIFICATION', 'Pending verification'), ('VERIFIED', 'Verified'), ('FAILING', 'Failing')], default='PENDING_VERIFICATION', max_length=32)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectors', to='places.place')),
            ],
            options={
                'db_table': 'connectors_connector',
            },
        ),
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('identity', models.CharField(help_text='Vendor-side router identity/hostname', max_length=255)),
                ('status', models.CharField(choices=[('PROVISIONING', 'Provisioning'), ('ONLINE', 'Online'), ('DEGRADED', 'Degraded'), ('OFFLINE', 'Offline'), ('DISABLED', 'Disabled')], default='PROVISIONING', max_length=32)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('capabilities', models.JSONField(blank=True, default=dict)),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routers', to='connectors.connector')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routers', to='places.place')),
            ],
            options={
                'db_table': 'connectors_router',
            },
        ),
        migrations.AddIndex(
            model_name='connector',
            index=models.Index(fields=['place', 'status'], name='connectors__place_i_311dc5_idx'),
        ),
        migrations.AddIndex(
            model_name='router',
            index=models.Index(fields=['place', 'status'], name='connectors__place_i_f59908_idx'),
        ),
        migrations.AddIndex(
            model_name='router',
            index=models.Index(fields=['last_seen_at'], name='connectors__last_se_8344e1_idx'),
        ),
        migrations.AddConstraint(
            model_name='router',
            constraint=models.UniqueConstraint(fields=('place', 'name'), name='unique_router_name_per_place'),
        ),
    ]
