# Generated by Django 5.0.9 on 2026-09-19 08:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SETUP', 'Setting up'), ('ARCHIVED', 'Archived')], default='SETUP', max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='organizations.organization')),
            ],
            options={
                'db_table': 'places_place',
                'indexes': [models.Index(fields=['organization', 'status'], name='places_plac_organiz_d249b7_idx'), models.Index(fields=['created_at'], name='places_plac_created_6fc9cf_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='place',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_place_name_per_org'),
        ),
    ]
