# Generated by Django 5.0.9 on 2026-09-19 16:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connectors', '0001_initial'),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mac_address', models.CharField(db_index=True, max_length=17)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='places.place')),
                ('router', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='connectors.router')),
            ],
            options={
                'db_table': 'devices_device',
                'indexes': [models.Index(fields=['place', 'last_seen_at'], name='devices_dev_place_i_da1ac0_idx'), models.Index(fields=['mac_address'], name='devices_dev_mac_add_307aef_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('place', 'mac_address'), name='unique_device_per_place'),
        ),
    ]
