# Generated by Django 5.0.9 on 2026-09-20 16:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('welcome_message', models.CharField(blank=True, max_length=500)),
                ('support_contact', models.CharField(blank=True, max_length=255)),
                ('terms_url', models.URLField(blank=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal_config', to='places.place')),
            ],
            options={
                'db_table': 'portal_portalconfig',
            },
        ),
    ]
