# Generated by Django 5.0.9 on 2026-09-20 04:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('organizations', '0001_initial'),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('data_cap_mb', models.PositiveIntegerField(blank=True, null=True)),
                ('max_concurrent_devices', models.PositiveIntegerField(blank=True, null=True)),
                ('is_publicly_listed', models.BooleanField(default=True)),
                ('available_from', models.DateTimeField(blank=True, null=True)),
                ('available_until', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_plans', to='organizations.organization')),
            ],
            options={
                'db_table': 'access_accessplan',
            },
        ),
        migrations.CreateModel(
            name='NetworkCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_cycles', to='places.place')),
            ],
            options={
                'db_table': 'access_networkcycle',
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('code_hash', models.CharField(max_length=64, unique=True)),
                ('code_last4', models.CharField(max_length=4)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ISSUED', 'Issued'), ('REDEEMED', 'Redeemed'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='AVAILABLE', max_length=20)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='access.accessplan')),
                ('redeemed_by_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='customers.customer')),
            ],
            options={
                'db_table': 'access_voucher',
            },
        ),
        migrations.AddIndex(
            model_name='accessplan',
            index=models.Index(fields=['organization', 'status'], name='access_acce_organiz_94d4cf_idx'),
        ),
        migrations.AddConstraint(
            model_name='accessplan',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', 0)), name='access_plan_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='accessplan',
            constraint=models.CheckConstraint(check=models.Q(('duration_minutes__gt', 0)), name='access_plan_duration_positive'),
        ),
        migrations.AddIndex(
            model_name='networkcycle',
            index=models.Index(fields=['place', 'status'], name='access_netw_place_i_78a7aa_idx'),
        ),
        migrations.AddConstraint(
            model_name='networkcycle',
            constraint=models.CheckConstraint(check=models.Q(('ends_at__gt', models.F('starts_at'))), name='network_cycle_ends_after_starts'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['plan', 'status'], name='access_vouc_plan_id_894302_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['batch_id'], name='access_vouc_batch_i_f8e61f_idx'),
        ),
    ]
