# Generated by Django 5.0.9 on 2026-09-20 04:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
        ('connectors', '0001_initial'),
        ('customers', '0001_initial'),
        ('devices', '0001_initial'),
        ('places', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HardLogoutEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope_type', models.CharField(choices=[('ROUTER', 'Single router'), ('ROUTERS', 'Selected routers'), ('PLACE', 'Whole place')], max_length=10)),
                ('router_ids', models.JSONField(blank=True, default=list, help_text="Explicit router UUIDs when scope_type is ROUTER/ROUTERS; empty for PLACE scope, which is resolved to the place's current routers at execution time.")),
                ('scheduled_at', models.DateTimeField()),
                ('scheduled_timezone', models.CharField(max_length=64)),
                ('impact_estimate_connections', models.PositiveIntegerField(blank=True, help_text='Labelled as an estimate everywhere in the UI (doc03 §9).', null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=500)),
                ('succeeded_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hard_logout_events', to='places.place')),
            ],
            options={
                'db_table': 'access_hardlogoutevent',
            },
        ),
        migrations.CreateModel(
            name='HardLogoutTargetResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ATTEMPTED', 'Attempted'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], default='ATTEMPTED', max_length=20)),
                ('attempted_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_results', to='access.hardlogoutevent')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='connectors.router')),
            ],
            options={
                'db_table': 'access_hardlogouttargetresult',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('EXPIRING', 'Expiring'), ('EXPIRED', 'Expired'), ('DISCONNECTED', 'Disconnected'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('access_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='access.accessplan')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='customers.customer')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='devices.device')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='places.place')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='connectors.router')),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='access.voucher')),
            ],
            options={
                'db_table': 'access_session',
            },
        ),
        migrations.AddIndex(
            model_name='hardlogoutevent',
            index=models.Index(fields=['place', 'status'], name='access_hard_place_i_ec74b9_idx'),
        ),
        migrations.AddIndex(
            model_name='hardlogoutevent',
            index=models.Index(fields=['scheduled_at'], name='access_hard_schedul_7a78e3_idx'),
        ),
        migrations.AddConstraint(
            model_name='hardlogouttargetresult',
            constraint=models.UniqueConstraint(fields=('event', 'router'), name='unique_target_per_event'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['router', 'status'], name='access_sess_router__caab55_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['place', 'status'], name='access_sess_place_i_9295d5_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['customer'], name='access_sess_custome_6f8754_idx'),
        ),
    ]
